sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '4'
- stable
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: EpxoEDz/dX39Oc9rUjenuNDbOpiXSPE3llDzOxGOfRWsxfUR3uqBP6Fx2/qAByUpsvDzKxWXyHkBA8eDjwy7qc3MQOM1ZjqLLXwhMQlBLhMO9hiCOS0OaewoGL+F3EYJ17RkDqs/EVB/SKCuA8Eh+wjnTJfq+V9WSj5GEYvm5niBqDzfaB4WA2SbLENCc5RNSz9qJWF55ftLWRaKUFb6Eu3a2NKtzq3FG4Z9I3WnTnHEVjcPOlw8A7HJ8a4VZtBiJQ3eHLAI/tAyQGJDoVva0WirRirumh6+COIe9mHj8hqCO1gpVQn6nBqDjOqE9wMA6ypTaou/xEph83IPRx0bhCrO4veu7scnSVvsEttbQmJdKW/kP4wFo7bFudG3NhFhyg/vtbCh9EjWKLC9tkkj0iV3mnqwGN5qE+yLSr1uvYL+zTyuppj+U9SQ4qNb02VsMZlUR6EPEB66+RNwh7xhCtFT8gpxe8H442UDRmAvl+urP1v5xTJp7+2crEZhOVDCbcGhl79VceMUOtEO/zM6HGoUCQDVUDfezpSE6lj+6bT8tZnqhYjRqOjIYB+IUX0swzBi5nYEIggzGAy3g0hZpMovOqjbkxsIiikibLPyuJiBZdKTMN94DXAYBGOy+1mOsrsShljfp7zdKnR8QEIUJCE23n0ICb6AbVt0RIidYLI=
  - secure: WzHYTYFg0uy0QZqeZa8dGTKriEdNiD4EJWJ8LLRyn/JtVLa0j6xKi63YxxJZJI/UAhRoO9Tur+T1L0/XeEwFzqcG9Nh+MgXhmm5Fn+qsG2pgh5QWrOEF2UFLtMRIgwz3ZjWGf35w3lW7LNN5hspC2kY3Na+8F9B/TFOviZ55PKDCfy37O0KyrLhKeG2hZ9NXFjvvHiJtqRejAcnXud5UIYl/MM6lmj1czg2Kp8DwsBStqQqmhbNXV+JxDJ4vYKLPj6qgiOXxT1/1L+lAiWeaPeOj9+Me8MZoJMlJkqFzeRHVcwirvo4XZG7zviAZYwzHop7K9Hz9SOMcBzvZhz49AzCkg2Jikn/FdSxOgq28warVNKAs4UIM9aT87i7ke8PkCRm6AtpYuEFkwnTleFDYNwip1oO4Jg9SAGOSWC5oaI7Zl9dozixGeDxnJ58q/SXEdgdATCl075LNsK2Vsgbmo9H5LneEKCSA1Y+2DENQwPYaLuKVM2TXPUvPhio3L6LtNeEGGa1SMpdqELb3qV/D4hzqUvKcKtvo4qEFjDJT2nKehd8wRh3ZlZmtAc9xoLJ4fVUScV8BGxCswMt/SfC/VJd9PAOMXfaysssjHaN3zCsB2v2IrgD44sHt7jvsi3sGeqMeiLQkAdIV9B4y1F5CQDaqKvi9rg5Ed1R4ui3AKvM=
